### ISSUE TITLE
Is this plugin broken on NodeBB v3.5.0 Harmony Theme?

### ISSUE THREAD

**Issue by saikarthikp9** [NodeBB-Community/nodebb-plugin-reactions#18]
<img width="1052" alt="" src="https://github.com/NodeBB-Community/nodebb-plugin-reactions/assets/69390532/238dd378-171a-42cc-ad0e-7c319fd775a3">

It shows up when I search it in the settings, but no settings page exists. 
I am using NodeBB v3.5.0
Harmony theme.

**Comment by barisusakli** [comment]
We are using it on https://community.nodebb.org so it is definitely working. What is the url that 404s?

**Comment by saikarthikp9** [comment]
@barisusakli, I could not find it on https://community.nodebb.org/ and assumed it was not activated there.
Where can I find it? Please share a screenshot if possible. 

The URL is: /admin/plugins/reactions

**Comment by barisusakli** [comment]
On our community it is only activate on chat messages, the url seems correct, if it is giving a 404 try rebuilding and restarting your nodebb and make sure it shows in the activated plugins.

**Comment by saikarthikp9** [comment]
It is working as expected. I installed another plugin that is similarly named [nodebb-plugin-reactions](https://www.npmjs.com/package/nodebb-plugin-reactions) by mistake that is no longer maintained.

Created a PR: https://github.com/NodeBB-Community/nodebb-plugin-reactions/pull/19

Thanks @barisusakli

**Comment by barisusakli** [comment]
@saikarthikp9 thanks
