### ISSUE TITLE
Unable to uninstall plugin

### ISSUE THREAD

**Issue by phenomlab** [NodeBB-Community/nodebb-plugin-reactions#8]
Installs ok, but you cannot uninstall at all ! See below screenshot.

![image](https://user-images.githubusercontent.com/2557946/166931003-b52d0e28-d24e-4f38-9f96-a477cf5c56bb.png)

See discussion - https://community.nodebb.org/topic/10225/nodebb-plugin-reactions-reactions-plugin-for-nodebb/38?_=1651756544137

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/10582
